name: Reusable ECS Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      service:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service }}:${{ github.sha }} \
          ./${{ inputs.service }}

      - name: Push Docker Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service }}:${{ github.sha }}

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
          --task-definition ${{ inputs.service }} \
          --query taskDefinition \
          > task-definition.json

      - name: Render Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.service }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service }}:${{ github.sha }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: ${{ vars.ECS_CLUSTER }}
          service: ${{ inputs.service }}
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          wait-for-service-stability: true
